version: '3.7'

services:
  nats-main:
    image: nats
    expose:
      - "4222"
      - "6222"
      - "8222"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: --jetstream
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4222"]
      interval: 30s
      timeout: 20s
      retries: 3

  nats-tools:
    image: synadia/nats-box:latest
    volumes:
      - ${PWD}/setup.sh:/tmp/setup.sh
    command: ["/tmp/setup.sh"]
    depends_on: 
      - nats-main

  batch-collector:
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      NATS_SERVER_URL: "nats://nats-main:4222"
      NATS_INCOMING_SUBJECT: "HL7MESSAGES"
      NATS_OUTGOING_SUBJECT_NAME: "HL7.ZIPPED_BATCHES"
      MSG_BATCH_SIZE: "100"
      MSG_BATCH_TIMEOUT: "60s"
    depends_on:
      - nats-tools
