version: '3.7'

services:
  nats-main:
    image: nats
    expose:
      - "4222"
      - "6222"
      - "8222"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: --jetstream
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4222"]
      interval: 30s
      timeout: 20s
      retries: 3

  nats-tools:
    image: synadia/nats-box:latest
    volumes:
      - ${PWD}/setup.sh:/tmp/setup.sh
    command: ["/tmp/setup.sh"]
    depends_on: 
      - nats-main

  #batch-collector:
  #  image: wh-imaging-dev-docker-local.artifactory.swg-devops.com/whpa-cdp-gateway-batch-collector:latest
  #  environment:
  #    NATS_URL: "nats://nats-main:4222"
  #    NATS_INCOMING_SUBJECT_NAME: "HL7.INCOMING"
  #    NATS_OUTGOING_SUBJECT_NAME: "HL7.ZIPPED.BATCHES"
  #    MSG_BATCH_SIZE: "10"
  #    MSG_BATCH_TIMEOUT: "30s"
  #    NATS_DURABLE_NAME: "batchCollector"
  #  depends_on:
  #    - nats-tools
